### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by darxwin** [Pwnoz0r/DiscordJiraApp#1]
I added the following arguments:
`DiscordJiraApp.exe -jiraAddress=<redacted_ip> -listenerPort=80 -discordWebhook=https://discordapp.com/api/webhooks/censored -discordUsername=Jira -discordAvatarUrl=https://cdn.discordapp.com/avatars/402332318456479767/cb5eb5b79f44803f7c0fc8745c3d0f00.webp?size=128`
and received this error:
`Unhandled Exception: System.Net.HttpListenerException: Access is denied
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at DiscordJiraApp.Application.Main(String[] args)`

Here's a screenshot of my Jira webhook:
![image](https://user-images.githubusercontent.com/34500182/34928633-95e0a964-f984-11e7-8c6a-84754281e167.png)

Do you have any tips? I'm glad you made this repo, and I was surprised it was updated so recently when I arrived here 👍

**Comment by jonrainier** [comment]
@darxwin Try to run the application as an administrator. Usually, with any sort of port listener, it needs elevated permissions to utilize the port.

* Edit: Modified your comment to redact your IP. 😏 
* Edit 2: Made a few [changes](https://github.com/Pwnoz0r/DiscordJiraApp/commit/073ea25de7701e7c4f600519f97fa5773c3b70d4) and pushed a release [here](https://github.com/Pwnoz0r/DiscordJiraApp/releases/tag/build-10)

**Comment by darxwin** [comment]
Right, so I've pretty much got it working other than this:

![image](https://user-images.githubusercontent.com/34500182/34958615-515c1f7a-f9f8-11e7-92bd-24dd1ae4bba6.png)

I believe this is the only thing preventing the message from being sent in the discord. Thanks for the help 👍

**Comment by jonrainier** [comment]
It's a quick security check to verify that your `-jiraAddress=` parameter is the same as the incoming request from your Jira Webhook. In your case, it looks like you're running them on the same machine, so set your `-jiraAddress=127.0.0.1` and it should work without an issue. Let me know how it goes.

**Comment by darxwin** [comment]
Everything's working now. Thanks for the help
